import { PettyCashTransactionType } from '@/core/domain/enums';

export class PettyCashFund {
    constructor(
        public readonly id: string,
        public readonly building_id: string,
        public current_balance: number,
        public readonly currency: string,
        public readonly updated_at: Date
    ) { }

    public static create(buildingId: string, currency: string = 'USD'): PettyCashFund {
        return new PettyCashFund(
            '', // To be generated by DB
            buildingId,
            0,
            currency,
            new Date()
        );
    }

    public canAfford(amount: number): boolean {
        return this.current_balance >= amount;
    }

    public addIncome(amount: number): void {
        this.current_balance += amount;
    }

    public registerExpense(amount: number): void {
        if (!this.canAfford(amount)) {
            throw new Error('Insufficient funds in petty cash');
        }
        this.current_balance -= amount;
    }

    public toJSON() {
        return {
            id: this.id,
            building_id: this.building_id,
            current_balance: this.current_balance,
            currency: this.currency,
            updated_at: this.updated_at
        };
    }
}
